version: '3.8'

services:
  broker:
    image: apache/kafka:4.0.0
    hostname: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

  apicurio-registry:
    image:  apicurio/apicurio-registry:3.0.6
    hostname: registry
    ports:
      - "8080:8080"
    depends_on:
      - broker
    environment:
      REGISTRY_KAFKASQL_BOOTSTRAP_SERVERS: broker:9092
      REGISTRY_UI_FEATURES_READONLY: "false"
  
  apicurio-registry-ui:
    image: apicurio/apicurio-registry-ui:3.0.6
    hostname: registry-ui
    ports:
      - "8888:8080"
    depends_on:
      - broker
      - registry
    environment:
      REGISTRY_API_URL: http://localhost:8080/apis/registry/v3 # needs the localhost, as i use it through the webbrowser
    